#!/usr/bin/env python3
"""
Support-restricted Monte Carlo bias / RMSE.

Recomputes the MC bias table (paper/Tables/mc_bias_rmse.tex) but averages the
estimated-minus-true surface ONLY over the grid cells that actually contain
observed (temperature, precipitation) data. Cells with no data are weighted 0
(binary support mask); occupied cells are weighted equally.

Reproduces the published full-grid numbers exactly as a self-check, then prints
and writes the support-restricted table to paper/Tables/mc_bias_rmse_support.tex.

Run from the repo root (no TensorFlow needed):
    python scripts/2026-08-12-compute_mc_bias_support.py
"""
import numpy as np, pandas as pd, glob, warnings
from pathlib import Path
warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parents[1]

# ---- evaluation grid: exactly create_pred_input(mc=True) ----
tv = np.linspace(0, 30, 90)          # temperature (deg C)
pv = np.linspace(0.012, 5.435, 90)   # precipitation (metres)
Tg, Pg = np.meshgrid(tv, pv)         # (P rows, T cols); matches surface.reshape(90,90)

# ---- true surfaces: static coefficients from Simulate_data.Surface() ----
def true_surface(spec, T=Tg, P=Pg):
    if spec == "linear":
        return 0.0008*T + 0.007*P
    if spec == "Burke":
        return 0.0127*T + 0.145*P - 0.0005*T**2 - 0.047*P**2
    if spec == "Leirvik":
        return (0.01*T + 0.105*P - 0.00048*T**2 - 0.07*P**2 - 0.0125*T*P
                + 0.00029*P*T**2 + 0.007*T*P**2 - 0.00013*T**2*P**2)
    if spec == "Trig":
        return (0.001*T + 0.0025*P + 0.02*np.sin(2*np.pi*P/5.0)
                + 0.01*np.cos(2*np.pi*T/15.0) - 0.005*T*np.sin(2*np.pi*P/5.0))
    raise ValueError(spec)

# ---- binary support mask from the observed (T,P) pairs ----
def support_mask():
    df = pd.read_excel(ROOT / "data" / "MainData.xlsx")
    T = pd.to_numeric(df["TempPopWeight"], errors="coerce")
    P = pd.to_numeric(df["PrecipPopWeight"], errors="coerce") / 1000.0  # mm -> m
    ok = T.notna() & P.notna()
    T, P = T[ok].values, P[ok].values
    inbox = (T >= tv.min()) & (T <= tv.max()) & (P >= pv.min()) & (P <= pv.max())
    te = np.r_[-np.inf, (tv[:-1]+tv[1:])/2, np.inf]
    pe = np.r_[-np.inf, (pv[:-1]+pv[1:])/2, np.inf]
    H, _, _ = np.histogram2d(P[inbox], T[inbox], bins=[pe, te])  # rows=P, cols=T
    return H >= 1, int((~inbox).sum())

def load_est(pattern):
    a = np.load(glob.glob(str(ROOT / pattern))[0])
    return a.mean(axis=0).reshape(90, 90)   # average over the 100 replications

def metrics(est, tru, mask=None):
    d = est - tru
    if mask is None:
        return d.mean(), np.sqrt((d**2).mean())
    return d[mask].mean(), np.sqrt((d**2)[mask].mean())

# DGP -> (Surface spec, arch, NN glob, Quad glob, published full-grid check)
ROWS = [
 ("Linear","linear","(2,)",
  "results/paper/weights/monte_carlo/NN/linear/surfaces_*.npy",
  "results/paper/weights/monte_carlo/Quadratic/surfaces_Linear_quadratic.npy",
  (-0.0105,0.0110, 0.0008,0.0011)),
 ("Burke","Burke","(4,)",
  "results/paper/weights/monte_carlo/NN/Burke/surfaces_*.npy",
  "results/paper/weights/monte_carlo/Quadratic/surfaces_Burke_quadratic.npy",
  (0.0364,0.0756, 0.0008,0.0013)),
 ("Leirvik","Leirvik","(4, 2)",
  "results/paper/weights/monte_carlo/NN/Leirvik/surfaces_*.npy",
  "results/paper/weights/monte_carlo/Quadratic/surfaces_Leirvik_quadratic.npy",
  (0.0963,0.2590, 0.1224,0.3575)),
 ("Trig","Trig","(2, 2)",
  "results/paper/weights/monte_carlo/NN/nonlinear/surfaces_*.npy",
  "results/paper/weights/monte_carlo/Quadratic/surfaces_Trig_quadratic.npy",
  (0.0353,0.0559, 0.0989,0.1747)),
]

def main():
    mask, n_out = support_mask()
    cov = int(mask.sum())
    print(f"support mask: {cov}/8100 cells occupied ({100*cov/8100:.1f}%); "
          f"{n_out} observations outside the grid box were dropped.\n")
    out = [f"Linear\t& 100 & $(2,)$"]  # placeholder replaced below
    tex_rows = []
    print(f"{'DGP':8}{'':2}{'NN full':>18}{'NN support':>18}{'Quad full':>18}{'Quad support':>18}")
    for name, spec, arch, nng, qdg, chk in ROWS:
        tru = true_surface(spec)
        eN, eQ = load_est(nng), load_est(qdg)
        fbN, frN = metrics(eN, tru);        mbN, mrN = metrics(eN, tru, mask)
        fbQ, frQ = metrics(eQ, tru);        mbQ, mrQ = metrics(eQ, tru, mask)
        assert abs(fbN-chk[0])<3e-3 and abs(frN-chk[1])<3e-3, f"NN full-grid mismatch {name}"
        assert abs(fbQ-chk[2])<3e-3 and abs(frQ-chk[3])<3e-3, f"Quad full-grid mismatch {name}"
        print(f"{name:8}  {fbN:+.4f}/{frN:.4f}   {mbN:+.4f}/{mrN:.4f}   "
              f"{fbQ:+.4f}/{frQ:.4f}   {mbQ:+.4f}/{mrQ:.4f}")
        tex_rows.append(f"  {name:7} & 100 & ${arch}$ & ${mbN:.4f}$ & ${mrN:.4f}$ "
                        f"& ${mbQ:.4f}$ & ${mrQ:.4f}$ \\\\".replace("$-0.0000$","$0.0000$"))
    tex = ("% Support-restricted Monte Carlo bias/RMSE.\n"
           f"% Auto-generated by scripts/{Path(__file__).name}\n"
           f"% Averaged over the {cov:,} of 8,100 grid cells ({100*cov/8100:.1f}%) that contain\n"
           "% at least one observed (temperature, precipitation) pair; empty cells weighted 0.\n"
           "\\begin{tabular}{lcrrrrr}\n  \\toprule\n"
           "   & & \\multicolumn{3}{c}{Neural network} & \\multicolumn{2}{c}{Quadratic} \\\\\n"
           "  \\cmidrule(lr){3-5} \\cmidrule(lr){6-7}\n"
           "  DGP & reps & Architecture & Bias & RMSE & Bias & RMSE \\\\\n  \\midrule\n"
           + "\n".join(tex_rows) +
           "\n  \\bottomrule\n\\end{tabular}\n")
    (ROOT/"paper"/"Tables"/"mc_bias_rmse_support.tex").write_text(tex, encoding="utf-8")
    print("\nwrote paper/Tables/mc_bias_rmse_support.tex")

if __name__ == "__main__":
    main()
