FROM mcr.microsoft.com/devcontainers/python:1-3.12-bookworm

WORKDIR /workspaces/Paper_1

RUN rm -f /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        poppler-utils \
        texlive-latex-recommended \
        texlive-latex-extra \
        texlive-science \
        texlive-fonts-recommended \
        latexmk \
        ghostscript \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mktexlsr

COPY requirements.txt /tmp/requirements.txt
RUN python -m pip install --upgrade pip \
    && pip install -r /tmp/requirements.txt

ENV PYTHONPATH=/workspaces/Paper_1/src